# -*- coding: utf-8 -*-
"""09)HistogramaSobreImagem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12FP0o8A1zYMgSAqQYQhpi1r4BFJvbqVy

a) gerar histograma(grafico) sobre a imagem escala de cinza

Obs.: dica, criar arquivo .csv e então gerar o gráfico sobre estes dados.

b) gerar histograma(grafico) sobre a imagem (RGB - cada canal de cor separado)
Obs.: dica, criar arquivo .csv e então gerar o gráfico sobre estes dados.
"""

import numpy as np
import pandas as pd
from PIL import Image
import matplotlib.pyplot as plt

def salvar_csv(histograma, nome_arquivo, coluna_nome):
    df = pd.DataFrame({coluna_nome: histograma})
    df.index.name = "Intensidade"
    df.to_csv(nome_arquivo)

def gerar_grafico(histograma, titulo, cor, nome_arquivo):
    plt.figure(figsize=(10, 6))
    plt.bar(range(256), histograma, color=cor, alpha=0.7)
    plt.title(titulo)
    plt.xlabel("Intensidade")
    plt.ylabel("Frequência")
    plt.savefig(nome_arquivo)
    plt.close()

def gerar_histograma_escala_cinza(caminho_imagem):
    imagem = Image.open(caminho_imagem).convert("L")
    imagem_array = np.array(imagem)

    histograma, _ = np.histogram(imagem_array, bins=256, range=(0, 255))

    salvar_csv(histograma, "histograma_cinza.csv", "Frequência")
    gerar_grafico(histograma, "Histograma - Escala de Cinza", "gray", "histograma_cinza.png")

def gerar_histograma_rgb(caminho_imagem):
    imagem = Image.open(caminho_imagem)
    imagem_array = np.array(imagem)

    hist_r, _ = np.histogram(imagem_array[:, :, 0], bins=256, range=(0, 255))
    hist_g, _ = np.histogram(imagem_array[:, :, 1], bins=256, range=(0, 255))
    hist_b, _ = np.histogram(imagem_array[:, :, 2], bins=256, range=(0, 255))

    df = pd.DataFrame({"R": hist_r, "G": hist_g, "B": hist_b})
    df.index.name = "Intensidade"
    df.to_csv("histograma_rgb.csv")

    gerar_grafico(hist_r, "Histograma - Canal R", "red", "histograma_r.png")
    gerar_grafico(hist_g, "Histograma - Canal G", "green", "histograma_g.png")
    gerar_grafico(hist_b, "Histograma - Canal B", "blue", "histograma_b.png")

gerar_histograma_escala_cinza("EntradaEscalaCinza.pgm")
gerar_histograma_rgb("EntradaRGB.ppm")