# -*- coding: utf-8 -*-
"""5)AmplificarIntensidadeBranco(brilho)NaImagem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uNXk1WkOtMBnlArmxyQ76SPHX9IZMvWC

Aplicar ganho de 20% de claridade (ganhobrilho = valorpixel *1,2) a imagem gerada na “Atividade 4”.
"""

import numpy as np
from PIL import Image

# Abrir a imagem em escala de cinza
imagem = Image.open("Entrada_EscalaCinza.pgm").convert("L")  # Converte para escala de cinza se necessário
imagem_array = np.array(imagem)

# Aplicar ganho de brilho de 20%
ganho_brilho = 1.2
imagem_brilho_array = np.clip(imagem_array * ganho_brilho, 0, 255).astype(np.uint8)

# Salvar a nova imagem com ganho de brilho
imagem_brilho = Image.fromarray(imagem_brilho_array)
imagem_brilho.save("Saida_brilho_20.pgm")