# -*- coding: utf-8 -*-
"""AtividadesProcDigitalImagens.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VNVhnmbx4NnS7DPzYAZaGy3aX2zYr5GX

Implementar imagem com valores aleatórios de tamanho 100x100
PBM - Tipo P1
PGM - Tipo P2 com 16 níveis intensidade cinza (4bits)
"""

import numpy as np

# Dimensões da imagem
width, height = 100, 100

# Função para gerar PBM (P1)
def generate_pbm(width, height):
    pbm_data = np.random.randint(2, size=(height, width))  # 0 ou 1
    pbm_header = f'P1\n{width} {height}\n'

    # Convertendo os dados para string
    pbm_body = '\n'.join(' '.join(map(str, row)) for row in pbm_data)

    return pbm_header + pbm_body

# Função para gerar PGM (P2)
def generate_pgm(width, height):
    pgm_data = np.random.randint(16, size=(height, width))  # Valores entre 0 e 15
    pgm_header = f'P2\n{width} {height}\n15\n'  # 15 é o máximo nível de cinza (4 bits)

    # Convertendo os dados para string
    pgm_body = '\n'.join(' '.join(map(str, row)) for row in pgm_data)

    return pgm_header + pgm_body

# Gerar imagens
pbm_image = generate_pbm(width, height)
pgm_image = generate_pgm(width, height)

# Salvar PBM
with open('random_image.pbm', 'w') as pbm_file:
    pbm_file.write(pbm_image)

# Salvar PGM
with open('random_image.pgm', 'w') as pgm_file:
    pgm_file.write(pgm_image)

print("Imagens PBM e PGM geradas com sucesso.")

"""a) Gerar imagem de tamanho 100x100 pixels do tipo

PPM (colorido rgb) – tipo P3(ASCII), com valores aleatórios, com 16 intesidades.
"""

import numpy as np

# Dimensões da imagem
width, height = 100, 100

# Função para gerar PPM (P3)
def generate_ppm(width, height):
    ppm_data = np.random.randint(16, size=(height, width, 3))  # Valores entre 0 e 15 para RGB
    ppm_header = f'P3\n{width} {height}\n15\n'  # 15 é o valor máximo para os níveis de cor (4 bits)

    # Convertendo os dados para string
    ppm_body = '\n'.join(' '.join(f'{r} {g} {b}' for r, g, b in row) for row in ppm_data)

    return ppm_header + ppm_body

# Gerar imagem PPM
ppm_image = generate_ppm(width, height)

# Salvar PPM
ppm_path = 'random_image.ppm'
with open(ppm_path, 'w') as ppm_file:
    ppm_file.write(ppm_image)

ppm_path

"""b) Gerar imagem de tamanho 1000x1000 pixels do tipo

PPM (colorido rgb) – tipo P3(ASCII), com valores aleatórios, com 256 intensidades.
"""

import numpy as np

# Dimensões da imagem 1000x1000 pixels
width, height = 1000, 1000

# Função para gerar PPM (P3) com 256 intensidades para RGB
def generate_large_ppm(width, height):
    ppm_data = np.random.randint(256, size=(height, width, 3))  # Valores entre 0 e 255 para RGB
    ppm_header = f'P3\n{width} {height}\n255\n'  # 255 é o valor máximo para os níveis de cor (8 bits)

    # Convertendo os dados para string
    ppm_body = '\n'.join(' '.join(f'{r} {g} {b}' for r, g, b in row) for row in ppm_data)

    return ppm_header + ppm_body

# Gerar imagem PPM de 1000x1000 pixels
large_ppm_image = generate_large_ppm(width, height)

# Salvar PPM
ppm_path = 'large_random_image.ppm'
with open(ppm_path, 'w') as ppm_file:
    ppm_file.write(large_ppm_image)

print(f"Imagem PPM gerada e salva como {ppm_path}")