# -*- coding: utf-8 -*-
"""07)ImagemRGB-média.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KI7xP1kY5-SSDMtNWVMT25-BkAXeNy-b

Nesta atividade será introduzido conceitos das imagens coloridas no formato RGB (Red, Green, Blue).

a) Aplicar cálculo da média entre os valores RGB dos arquivos "Fig4.ppm" tipo P3 e gerar imagem saída escala de cinza (P2) para cada pixel da imagem.

b) Aplicar cálculo da média entre os valores RGB dos arquivos "Fig4.ppm"  tipo P3 e gerar imagem saída com a média dos valores RGB em cada pixel da imagem. Saída tipo P3.
"""

import numpy as np
from PIL import Image

imagem = Image.open("Fig4.ppm")
imagem_array = np.array(imagem)

# Função responsável por calcular a média RGB e gerar uma imagem em escala de cinza (P2)
def gerar_escala_cinza(imagem_array):
    imagem_cinza_array = np.mean(imagem_array, axis=2).astype(np.uint8)

    with open("Saida_escala_cinza.pgm", "w") as f:
        f.write("P2\n")
        f.write(f"{imagem_cinza_array.shape[1]} {imagem_cinza_array.shape[0]}\n")  # Largura e altura
        f.write("255\n")  # Valor máximo para a escala de cinza
        for linha in imagem_cinza_array:
            f.write(" ".join(map(str, linha)) + "\n")  # Escreve cada linha no arquivo

# Função para calcular a média RGB e gerar uma imagem P3 com valores médios
def gerar_media_rgb(imagem_array):
    # Calcular a média dos valores RGB para cada pixel e replicar em R, G, B
    media_rgb_array = np.mean(imagem_array, axis=2, keepdims=True).astype(np.uint8)
    imagem_media_rgb_array = np.repeat(media_rgb_array, 3, axis=2)  # Expande para 3 canais (R, G, B)

    # Salvar a imagem P3 com média RGB
    with open("Saida_media_rgb.ppm", "w") as f:
        f.write("P3\n")  # Formato P3 (colorido)
        f.write(f"{imagem_media_rgb_array.shape[1]} {imagem_media_rgb_array.shape[0]}\n")  # Largura e altura
        f.write("255\n")  # Valor máximo para o canal RGB
        for linha in imagem_media_rgb_array:
            for pixel in linha:
                f.write(" ".join(map(str, pixel)) + " ")
            f.write("\n")


gerar_escala_cinza(imagem_array)
gerar_media_rgb(imagem_array)